/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProcessMiningRouteImport } from './routes/process-mining'
import { Route as IndexRouteImport } from './routes/index'

const ProcessMiningRoute = ProcessMiningRouteImport.update({
  id: '/process-mining',
  path: '/process-mining',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/process-mining': typeof ProcessMiningRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/process-mining': typeof ProcessMiningRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/process-mining': typeof ProcessMiningRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/process-mining'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/process-mining'
  id: '__root__' | '/' | '/process-mining'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProcessMiningRoute: typeof ProcessMiningRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/process-mining': {
      id: '/process-mining'
      path: '/process-mining'
      fullPath: '/process-mining'
      preLoaderRoute: typeof ProcessMiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProcessMiningRoute: ProcessMiningRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
